
package cn.winfxk.lexy.wms.im.client.release;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TIPTOPServiceGateWay", targetNamespace = "http://www.dsc.com.tw/tiptop/TIPTOPServiceGateWay", wsdlLocation = "http://192.168.0.165/web/ws/r/aws_ttsrv4?wsdl")
public class TIPTOPServiceGateWay
    extends Service
{

    private final static URL TIPTOPSERVICEGATEWAY_WSDL_LOCATION;
    private final static WebServiceException TIPTOPSERVICEGATEWAY_EXCEPTION;
    private final static QName TIPTOPSERVICEGATEWAY_QNAME = new QName("http://www.dsc.com.tw/tiptop/TIPTOPServiceGateWay", "TIPTOPServiceGateWay");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.165/web/ws/r/aws_ttsrv4?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TIPTOPSERVICEGATEWAY_WSDL_LOCATION = url;
        TIPTOPSERVICEGATEWAY_EXCEPTION = e;
    }

    public TIPTOPServiceGateWay() {
        super(__getWsdlLocation(), TIPTOPSERVICEGATEWAY_QNAME);
    }

    public TIPTOPServiceGateWay(WebServiceFeature... features) {
        super(__getWsdlLocation(), TIPTOPSERVICEGATEWAY_QNAME, features);
    }

    public TIPTOPServiceGateWay(URL wsdlLocation) {
        super(wsdlLocation, TIPTOPSERVICEGATEWAY_QNAME);
    }

    public TIPTOPServiceGateWay(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TIPTOPSERVICEGATEWAY_QNAME, features);
    }

    public TIPTOPServiceGateWay(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TIPTOPServiceGateWay(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TIPTOPServiceGateWayPortType
     */
    @WebEndpoint(name = "TIPTOPServiceGateWayPortType")
    public TIPTOPServiceGateWayPortType getTIPTOPServiceGateWayPortType() {
        return super.getPort(new QName("http://www.dsc.com.tw/tiptop/TIPTOPServiceGateWay", "TIPTOPServiceGateWayPortType"), TIPTOPServiceGateWayPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TIPTOPServiceGateWayPortType
     */
    @WebEndpoint(name = "TIPTOPServiceGateWayPortType")
    public TIPTOPServiceGateWayPortType getTIPTOPServiceGateWayPortType(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.dsc.com.tw/tiptop/TIPTOPServiceGateWay", "TIPTOPServiceGateWayPortType"), TIPTOPServiceGateWayPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TIPTOPSERVICEGATEWAY_EXCEPTION!= null) {
            throw TIPTOPSERVICEGATEWAY_EXCEPTION;
        }
        return TIPTOPSERVICEGATEWAY_WSDL_LOCATION;
    }

}
